version: '3.9'

services:
  node:
    image: node:lts-slim
    working_dir: /app
    env_file:
      - .env
    command: /bin/sh -c 'npm install && npm start'
    ports:
      - '3004:3004'
    volumes:
      - ./src:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:lts
    restart: always
    healthcheck:
      interval: 30s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  db_test:
    image: mariadb:lts
    restart: always
    healthcheck:
      interval: 30s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s
    environment:
      MYSQL_DATABASE: ${TEST_DB_NAME}
      MYSQL_USER: ${TEST_DB_USER}
      MYSQL_PASSWORD: ${TEST_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - ./db_test:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_ARBITRARY: 1

  pmaTest:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8082:80'
    restart: always
    depends_on:
      - db_test
    environment:
      PMA_HOST: db_test
      PMA_USER: ${TEST_DB_USER}
      PMA_PASSWORD: ${TEST_DB_PASSWORD}
      PMA_ARBITRARY: 1
